export const MESSAGE_TYPES = Object.freeze({
  AI_REQUEST: "AI_REQUEST",
  ENQUEUE_CURRENT_JOB: "ENQUEUE_CURRENT_JOB",
  OPEN_SIDE_PANEL: "OPEN_SIDE_PANEL",
  OPEN_TASK_RESULT: "OPEN_TASK_RESULT",
  WAKE_TASK_QUEUE: "WAKE_TASK_QUEUE"
});
